
#Security Context - Linux Capabilities

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        ports:
        - containerPort: 8080
        securityContext:
            privileged: true


#privileged: true
#nesse exemplo estou usando o docker in docker,é quando rodamos um container docker dentro de outro container docker.
#deve tomar cuidado ao usar o privileged, pois o container terá acesso total ao host, podendo causar problemas de segurança.

#caso o privileged: false, o container nao sera criado, pois o docker in docker precisa de privilegio para rodar.