apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
      versao: blue
  strategy:
    type: RollingUpdate    
    rollingUpdate:
      maxSurge: 50% # 50% a mais de pods do que o desejado
      maxUnavailable: 20% # 20% dos pods podem estar fora do ar
  template:
    metadata:
      labels:
        app: web
        versao: blue
    spec:
      containers:
      - name: web
        image: cesarags/web-color:blue
        ports:
        - containerPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-green
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
      versao: green
  strategy:
    type: RollingUpdate    
    rollingUpdate:
      maxSurge: 50% # 50% a mais de pods do que o desejado
      maxUnavailable: 20% # 20% dos pods podem estar fora do ar
  template:
    metadata:
      labels:
        app: web
        versao: green
    spec:
      containers:
      - name: web
        image: cesarags/web-color:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
    versao: green #muda o balanceador de carga para apontar para a versao green ou blue
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

# Blue-Green
# Essa estrategia é a mais segura, ela cria um novo ambiente com a nova versão, e depois altera o balanceador de carga para apontar para o novo ambiente.
# Dessa forma, o ambiente antigo continua funcionando, e o novo ambiente é testado antes de ser colocado em produção.

