# demo para resource limite CPU

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-do-caos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simulador-do-caos
  template:
    metadata:
      labels:
        app: simulador-do-caos
    spec:
      containers:
      - name: simulador-do-caos
        image: kubedevio/simulador-do-caos:v1
        ports:
        - containerPort: 3000
        resources:
          requests: # requisitos minimos
            cpu: "0.2" # esse Pod precisa no minimo 0.2 CPU para ser criado.
            memory: "200Mi" # esse Pod precisa de no minimo 200Mi de memoria para ser criado.
            
# Caso a maquina nao tenha esses recursos disponiveis, o pod nao sera criado.
# Até que tenha recursos disponiveis. Nesse cenario teria que adicionar mais maquinas ou aumentar os recursos da maquina.
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000