apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-hardware
spec:
  hard:
    requests.cpu: "1" # 
    requests.memory: 1Gi #
    limits.cpu: "2" # 
    limits.memory: 4Gi #


# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: quota-objetos
# spec:
#   hard:
#     pods: "10" # nao posso criar mais de 10 pods no meu namespace
#     services: "5" # nao posso criar mais de 5 services no meu namespace
#     secrets: "3" # nao posso criar mais de 3 secrets no meu namespace
#     configmaps: "4" # nao posso criar mais de 4 configmaps no meu namespace
#     services.loadbalancers: "2" # nao posso criar mais de 2 services do tipo LoadBalancer no meu namespace
#     count/deployments.app: "3" #  nao posso criar mais de 3 deployments no meu namespace
#     count/replicaset.app: "3" # nao posso criar mais de 3 replicaset no meu namespace