apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-caos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-caos
  template:
    metadata:
      labels:
        app: web-caos
    spec:
      containers:
      - name: web-caos
        image: kubedevio/simulador-do-caos:v1
        ports:
        - containerPort: 3000
        startupProbe:
          httpGet:
            port: 3000
            path: /health
          periodSeconds: 10 # tempo entre as verificações
          failureThreshold: 30 # quantidade de falhas para reiniciar o container. 
          
---
apiVersion: v1
kind: Service
metadata:
  name: web-caos
spec:
  selector:
    app: web-caos
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000