kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane  # esse control-plane é o master, caso ele caia, sera eleito um novo master
  extraPortMappings: #  configura o port binding. serve para mapear a porta 30000 do container para a porta 8080 do host local
    - containerPort: 30000 # do container
      hostPort: 8080 # da maquina local
      protocol: TCP
      listenAddress: "0.0.0.0" # localhost
    - containerPort: 30001 # do container
      hostPort: 8081 # da maquina local
      protocol: TCP
      listenAddress: "0.0.0.0"
    - containerPort: 30002 # do container
      hostPort: 8082 # da maquina local
      protocol: TCP
      listenAddress: "0.0.0.0"
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker