apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: cesarags/web-color:blue
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
      nodeSelector:
        disktype: ssd      

# sรณ sera criado pods em nodes que tenham o label disktype=ssd

# kubectl label nodes <nome_node> disktype=hd, para adicionar um label no node
# kubectl label nodes <nome_node> disktype=ssd            