apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:  
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: kubedevio/web-color:blue
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: web # exemplo de teste curl http://webcolor
spec:
    selector:
      app: web
    ports:
      - protocol: TCP
        port: 80 # Porta do serviço
        targetPort: 80 # Porta do container
        nodePort: 30001 # Porta do nó
    type: NodePort
    
    # Kubernetes encaminha o tráfego recebido na porta 30001 para a porta 80 do serviço, 
    # que então encaminha para a targetPort (80 ou 8080 ou a porta espeficiada) nos containers.