apiVersion: v1
kind: Pod
metadata:
  name: meupod
  labels:
    app: web
    versao: blue
spec:
  containers:
    - name: web
      image: kubedevio/web-color:blue
      ports:
        - containerPort: 80
          name: http
          protocol: TCP