apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-caos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-caos
  template:
    metadata:
      labels:
        app: web-caos
    spec:
      containers:
      - name: web-caos
        image: registry.k8s.io/goproxy:0.1
        ports:
        - containerPort: 8080
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 3   # tempo para iniciar a verificação 
          periodSeconds: 4 # tempo entre as verificações
          failureThreshold: 1 # quantidade de falhas para reiniciar o container. 
          successThreshold: 1 # quantidade de sucessos para parar de reiniciar o container.
          timeoutSeconds: 10 # tempo para o probe falhar. 
          
---
apiVersion: v1
kind: Service
metadata:
  name: web-caos
spec:
  selector:
    app: web-caos
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000