apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-caos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-caos
  template:
    metadata:
      labels:
        app: web-caos
    spec:
      containers:
      - name: web-caos
        image: registry.k8s.io/busybox
        ports:
        - containerPort: 3000
        command: ["/bin/sh", "-c", "touch /tmp/ready; sleep 30; rm -f /tmp/ready; sleep 30;"] # exclui o arquivo ready após 30 segundos e dorme por 30 segundos
        readinessProbe:
          exec:
           command:
              - cat
              - /tmp/ready
          initialDelaySeconds: 5   # tempo para iniciar a verificação 
          periodSeconds: 5 # tempo entre as verificações
          failureThreshold: 1 # quantidade de falhas para reiniciar o container. 
          successThreshold: 1 # quantidade de sucessos para parar de reiniciar o container.
          timeoutSeconds: 5 # tempo para o probe falhar. 
          
---
apiVersion: v1
kind: Service
metadata:
  name: web-caos
spec:
  selector:
    app: web-caos
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000