apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  persistentVolumeClaimRetentionPolicy: # serve para definir o que fazer com os volumes
    whenScaled: Delete # 
    whenDeleted: Retain # 
  serviceName: "nginx" # nome do serviço que será criado
  selector:
    matchLabels:
      app: nginx-state
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-state
    spec:
      initContainers:
        - name: volume-page
          image: busybox
          command: ['sh', '-c', 'echo "Hello from $(hostname) the init container" > /app/index.html']
          volumeMounts:
          - name:  www
            mountPath:  /app
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
          - name:  www
            mountPath:  /usr/share/nginx/html  
  volumeClaimTemplates: # cria um volume para cada pod. ex: nginx-0, nginx-1, nginx-2.
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "do-block-storage" # "kc get storageclass" para obter o nome do storage class
        resources:
          requests:
            storage: 1Gi      

--- 
# Headless service
# clusterIP: None, indica que o serviço não terá um IP fixo. A comunicação sera feita pelo nome do serviço ou DNS interno.
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx-state
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80



# kc run ubuntu-curl --image cesarags/ubuntu-curl:v1 -it -- /bin/bash    
# curl http://nginx-0.nginx.default.svc.cluster.local

###########################################################################################

# StatefulSet nao cria replicas, ele cria pods com nomes sequenciais. ex:  nginx-0  nginx-1  nginx-2
# Ideal para aplicações que precisam de um estado, como bancos de dados.

########### Sobre persistentVolumeClaimRetentionPolicy ###########

# - whenScaled: Delete, Retain, Recycle
# Delete: deleta os volume  que ficaram orfãos quando o pod é escalado para baixo.
# Retain: mantem o volume quando o pod é deletado
# Recycle: deleta o volume quando o pod é deletado e cria um novo volume vazio

# - whenDeleted: Delete, Retain, Recycle
# Delete: deleta os volume  que ficaram orfãos quando o pod é deletado.
# Retain: mantem o volume quando o pod é deletado
# Recycle: deleta o volume quando o pod é deletado e cria um novo volume vazio

###########################################################################################