apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: production # cria os pod no namespace production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: kubedevio/web-color:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: production # cria os pod no namespace production
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80


# usage kc port-forward -n production svc/web  8080:80    
# ou kubectl port-forward -n production <nome-do-pod> 8080:80